name: release-flagbase-client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  release:
    name: "Deploy: client.flagbase.com"
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FLAGBASE_COM_ACCESS_TOKEN }}
          repository: ${{ secrets.FLAGBASE_COM_REPO }}
          event-type: ${{ secrets.FLAGBASE_COM_RELEASE_UI_APP_EVENT_TYPE }}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
